### ISSUE TITLE
Chair Transition Checklist - Pushkar Joglekar

### ISSUE THREAD

**Issue by PushkarJ** [cncf/tag-security#1092]
# Chair Transition Checklist

Opening this on request of @lumjjb 

## Nomination

This serves to augment the [Security TAG Chair proposal
process](chair-proposal-process.md) with specific items that must be completed.

* [x] Nomination
  * [x] TOC-Liaison slack discussion and approval
  * [x] Co-chair & Tech Lead meeting announcement
  * [x] Security TAG Meeting announcement -- all regions
  * [x] TOC email list official nomination
  * [x] #tag-security slack message with a link to the email nomination
  * [x] TOC meeting presentation
* [x] Vote - official count recorded and posted

## Transfer

* [ ] Transfer Logistics
  * [x] #tag-chairs slack channel - add new chair(s)
  * [x] cncf-tag-chairs mailing list - add new chair(s) - service desk ticket.
  * [x] #tag-security-cochairs channel - add new chair(s)
  * [x] #tag-security-cochairs-emeritus - add outgoing chair(s)
  * [x] #tag-security-toc-liaison - add new chair(s)
  * [x] Co-chair meeting - add new co-chairs and add doc sharing
  * [x] transfer ownership of co-chair meeting calendar invite
    and tech lead calendar invite - if applicable
    * [x] New meeting link will need created by new calendar owner if using
      Google meet.  meet.new will create this, just copy into invite or
      transition to Zoom
  * [x] TOC Liaison meeting
    * [x] Check if the time still works for new chair(s)
    * [x] Transfer calender ownership if needed
    * [x] Add new co-chair(s) to calendar invitation
    * [x] Share meeting notes doc
  * [x] Choose new chair representative for Security TAG [on-going
    projects](https://github.com/cncf/tag-security#on-going-projects) if needed.
  * [x] ~~add chair to [github team](https://github.com/orgs/cncf/teams/sig-security/)~~ - **NO LONGER MAINTED**
  * [x] tag-security repo PR:
    * [x] Update codeowners, github settings, README (TOC Liaisons and chairs
      have admin access, tech leads have push access). https://github.com/cncf/people/pull/261
    * [x] Link to official vote email list message in PR descriptions 
  * [x] [TOC Repo update](https://github.com/cncf/toc/blob/main/tags/security.md) https://github.com/cncf/toc/pull/1124
  * [x] [Service Desk Access](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1)
  * [x] Update email lists
    * [x] update email list membership
    * [x] chairs should have moderator role
    * [x] remove old chairs from chairs list
  * [x] Verify new chairs have zoom credentials
  * [x] YouTube Channel
    * [x] invite new chairs (if needed)
    * [x] give "owners" permission

## De-provisioning

Reverse all above transfer steps to TL level, and in addition:

* [x] Transfer ownership of all documents
  * [x] Co-Chairs meeting notes
  * [x] Leadership meeting notes,
  * [x] TOC Liaison meeting notes
  * [x] Credentials doc
* [x] Transfer ownership of calendar invites
  * [x] Co-chairs meeting
  * [x] Leadership meeting

## Announce

* [x] Announce the vote
  * [x] #tag-security slack message
  * [x] email message to the tag-security list
  * [x] Security TAG meeting Announcement for each region

**Comment by anvega** [comment]
@PushkarJ Is the checklist representative of current status? I see three weeks since the last update.

**Comment by PushkarJ** [comment]
Yes its accurate. Keep it open as is please

**Comment by anvega** [comment]
I ticked off 5 boxes in nomination and announcement which I've known to have taken place.

**Comment by PushkarJ** [comment]
Thank you everyone and especially @lumjjb for helping me complete this exhaustive checklist
