### ISSUE TITLE
[Security Self-Assessment] KubeVirt

### ISSUE THREAD

**Issue by molofgarb** [cncf/tag-security#1140]
### Details
Project Name: KubeVirt

Github URL: https://github.com/kubevirt/kubevirt

CNCF project stage: Incubation preparing for Graduation
- Incubation Proposal: https://github.com/kubevirt/kubevirt/issues/5172

Security Provider: No

Self-assessment link (before PR): [KubeVirt Security Self-Assessment](https://github.com/molofgarb/tag-security-11/blob/main/assessments/projects/kubevirt/self-assessment.md)

### Tasks
- [ ] Stage 1: Preparation
   - [x] Create a GitHub issue for the security self assessment of KubeVirt project.
      - [x] Issue Link in CNCF Tag-Security: <link>
   - [x] Create a place holder of security self assessment.
      - [x] Create a fork of the CNCF Tag-Security in your Github.
      - [x] Create a new folder for the KubeVirt project.
      - [x] Add the security self assessment template under the project folder.
      - [x] Issue link of Initial Commit: https://github.com/molofgarb/tag-security-11/tree/5390e86397b707f60067ec6917b03803e7802fde
   - [ ] Review Documentation of the KubeVirt project.
- [ ]  Stage 2: Understand the Project Landscape
   - [ ] Understand the overall project at a sufficient level of detail.
   - [ ] Update overview section
      - [ ] **Background** <br> commit: <commit_link>
      - [ ] **Actors** <br> commit: <commit_link>
      - [ ] **Actions** <br> commit: <commit_link>
      - [ ] **Goals** <br> commit: <commit_link>
      - [ ] **Non-Goals** <br> commit: <commit_link>
- [ ]  Stage 3: First complete draft of the Self Assessment
   - [ ] Document technical specifications of the KubeVirt project.
      - [ ] **Self assessment use** <br> commit: <commit_link>
      - [ ] **Security functions and features** <br> commit: <commit_link>
      - [ ] **Project compliance** <br> commit: <commit_link>
      - [ ] **Secure development practices** <br> commit: <commit_link>
      - [ ] **Security issue resolution** <br> commit: <commit_link>
      - [ ] **Appendix** <br> commit: <commit_link>
   - [ ] Complete the security self assessment draft.

- [ ]  Stage 4: Iteration with the project
   - [ ] Initiate discussion with KubeVirt project maintainers.
   - [ ] Incorporate inputs and feedback from KubeVirt project maintainers.
   - [ ] Document the findings.

- [ ] Stage 5: Finalization
   - [ ] Initiate PR
   - [ ] Get feedback and findings from reviewers
   - [ ] Fix the findings
   - [ ] Merge the PR
   - [ ] Close the issue

**Comment by molofgarb** [comment]
Kubevirt has already been assessed and in progress

**Comment by JustinCappos** [comment]
@molofgarb I apologize for the confusion.  You should do the Security Pals work on the project, but please fork the repo and only open an issue in the last step (when we're ready to ask TAG Security to review and merge).  

Pranava and I will update the guidance to be clearer.
