### ISSUE TITLE
[Security Self Assessment] emissary-ingress / emissary

### ISSUE THREAD

**Issue by yashaswi2000** [cncf/tag-security#1141]
### Details
Project Name: emissary-ingress/emissary

Github URL: [emissary](https://github.com/emissary-ingress/emissary)

CNCF project stage: Incubation preparing for Graduation
- Incubation Proposal: https://github.com/cncf/toc/pull/435

Security Provider: No

Self-assessment link (before PR): 

### Tasks
- [ ] Stage 1: Preparation
   - [ ] Create a GitHub issue for the security self assessment of emissary-ingress/emissary project.
      - [ ] Issue Link in CNCF Tag-Security: <link>
   - [ ] Create a place holder of security self assessment.
      - [ ] Create a fork of the CNCF Tag-Security in your Github.
      - [ ] Create a new folder for the emissary-ingress/emissary project.
      - [ ] Add the security self assessment template under the project folder.
      - [ ] Issue link of Initial Commit: <link>
   - [ ] Review Documentation of the emissary-ingress/emissary project.
- [ ]  Stage 2: Understand the Project Landscape
   - [ ] Understand the overall project at a sufficient level of detail.
   - [ ] Update overview section
      - [ ] **Background** <br> commit: <commit_link>
      - [ ] **Actors** <br> commit: <commit_link>
      - [ ] **Actions** <br> commit: <commit_link>
      - [ ] **Goals** <br> commit: <commit_link>
      - [ ] **Non-Goals** <br> commit: <commit_link>
- [ ]  Stage 3: First complete draft of the Self Assessment
   - [ ] Document technical specifications of the emissary-ingress/emissary project.
      - [ ] **Self assessment use** <br> commit: <commit_link>
      - [ ] **Security functions and features** <br> commit: <commit_link>
      - [ ] **Project compliance** <br> commit: <commit_link>
      - [ ] **Secure development practices** <br> commit: <commit_link>
      - [ ] **Security issue resolution** <br> commit: <commit_link>
      - [ ] **Appendix** <br> commit: <commit_link>
   - [ ] Complete the security self assessment draft.

- [ ]  Stage 4: Iteration with the project
   - [ ] Initiate discussion with emissary-ingress/emissary project maintainers.
   - [ ] Incorporate inputs and feedback from emissary-ingress/emissary project maintainers.
   - [ ] Document the findings.

- [ ] Stage 5: Finalization
   - [ ] Initiate PR
   - [ ] Get feedback and findings from reviewers
   - [ ] Fix the findings
   - [ ] Merge the PR
   - [ ] Close the issue
