### ISSUE TITLE
[Security Self-Assessment] Antrea

### ISSUE THREAD

**Issue by molofgarb** [cncf/tag-security#1142]
### Details
Project Name: Antrea

Github URL: https://github.com/antrea-io/antrea

CNCF project stage: Sandbox preparing for Incubation
- Sandbox Proposal: https://github.com/cncf/toc/issues/650

Security Provider: No

Self-assessment link (before PR): [Antrea Security Self-Assessment](https://github.com/molofgarb/tag-security-11/blob/main/assessments/projects/antrea/self-assessment.md)

### Tasks
- [ ] Stage 1: Preparation
   - [x] Create a GitHub issue for the security self assessment of Antrea project.
      - [x] Issue Link in CNCF Tag-Security: https://github.com/cncf/tag-security/issues/1142
   - [x] Create a place holder of security self assessment.
      - [x] Create a fork of the CNCF Tag-Security in your Github.
      - [x] Create a new folder for the Antrea project.
      - [x] Add the security self assessment template under the project folder.
      - [x] Issue link of Initial Commit: https://github.com/molofgarb/tag-security-11/tree/5390e86397b707f60067ec6917b03803e7802fde
   - [ ] Review Documentation of the Antrea project.
- [ ]  Stage 2: Understand the Project Landscape
   - [ ] Understand the overall project at a sufficient level of detail.
   - [ ] Update overview section
      - [ ] **Background** <br> commit: <commit_link>
      - [ ] **Actors** <br> commit: <commit_link>
      - [ ] **Actions** <br> commit: <commit_link>
      - [ ] **Goals** <br> commit: <commit_link>
      - [ ] **Non-Goals** <br> commit: <commit_link>
- [ ]  Stage 3: First complete draft of the Self Assessment
   - [ ] Document technical specifications of the Antrea project.
      - [ ] **Self assessment use** <br> commit: <commit_link>
      - [ ] **Security functions and features** <br> commit: <commit_link>
      - [ ] **Project compliance** <br> commit: <commit_link>
      - [ ] **Secure development practices** <br> commit: <commit_link>
      - [ ] **Security issue resolution** <br> commit: <commit_link>
      - [ ] **Appendix** <br> commit: <commit_link>
   - [ ] Complete the security self assessment draft.

- [ ]  Stage 4: Iteration with the project
   - [ ] Initiate discussion with Antrea project maintainers.
   - [ ] Incorporate inputs and feedback from Antrea project maintainers.
   - [ ] Document the findings.

- [ ] Stage 5: Finalization
   - [ ] Initiate PR
   - [ ] Get feedback and findings from reviewers
   - [ ] Fix the findings
   - [ ] Merge the PR
   - [ ] Close the issue

**Comment by molofgarb** [comment]
issue will be tracked in https://github.com/Rana-KV/tag-security/issues/2
