### ISSUE TITLE
[Security Self-Assessment] Jaeger

### ISSUE THREAD

**Issue by jw6680** [cncf/tag-security#1143]
### Details
Project Name: Jaeger

Github URL: https://github.com/jaegertracing/jaeger

CNCF project stage: Sandbox preparing for Incubation / Incubation preparing for Graduation / Graduated
- Graduation Proposal: https://github.com/jaegertracing/jaeger

Security Provider: No

Self-assessment link (before PR): [Jaeger Security Self-Assessment](https://github.com/cp-57/tag-security/blob/main/assessments/projects/jaeger/self-assessment.md)

### Tasks
- [ ] Stage 1: Preparation
   - [x] Create a GitHub issue for the security self assessment of Jaeger project.
      - [x] Issue Link in CNCF Tag-Security: https://github.com/cncf/tag-security/issues/1143
   - [x] Create a place holder of security self assessment.
      - [x] Create a fork of the CNCF Tag-Security in your Github.
      - [x] Create a new folder for the Jaeger project.
      - [x] Add the security self assessment template under the project folder.
      - [x] Issue link of Initial Commit: https://github.com/cp-57/tag-security/commit/5ea77286705c1537774244a8488a30dd887991b2
   - [x] Review Documentation of the Jaeger project.
- [ ]  Stage 2: Understand the Project Landscape
   - [ ] Understand the overall project at a sufficient level of detail.
   - [ ] Update overview section
      - [ ] **Background** <br> commit: <commit_link>
      - [ ] **Actors** <br> commit: <commit_link>
      - [ ] **Actions** <br> commit: <commit_link>
      - [ ] **Goals** <br> commit: <commit_link>
      - [ ] **Non-Goals** <br> commit: <commit_link>
- [ ]  Stage 3: First complete draft of the Self Assessment
   - [ ] Document technical specifications of the <project_name> project.
      - [ ] **Self assessment use** <br> commit: <commit_link>
      - [ ] **Security functions and features** <br> commit: <commit_link>
      - [ ] **Project compliance** <br> commit: <commit_link>
      - [ ] **Secure development practices** <br> commit: <commit_link>
      - [ ] **Security issue resolution** <br> commit: <commit_link>
      - [ ] **Appendix** <br> commit: <commit_link>
   - [ ] Complete the security self assessment draft.

- [ ]  Stage 4: Iteration with the project
   - [ ] Initiate discussion with <project_name> project maintainers.
   - [ ] Incorporate inputs and feedback from <project_name> project maintainers.
   - [ ] Document the findings.

- [ ] Stage 5: Finalization
   - [ ] Initiate PR
   - [ ] Get feedback and findings from reviewers
   - [ ] Fix the findings
   - [ ] Merge the PR
   - [ ] Close the issue
