### ISSUE TITLE
Tech Lead Transition Checklist: John Kjell

### ISSUE THREAD

**Issue by jkjell** [cncf/tag-security#1255]
# Tech Lead transition checklist

This checklist should be copied into a new issue for when a new tech lead(s) is needed.

## Nomination

For nomination process please refer to [tech-lead-proposal-process](./tech-lead-proposal-process.md)

## Transfer

* [x] Transfer Logistics
  * [x] #tag-security-chairs-and-tech-leads channel - add new TL(s)
  * [x] tag-leadership mailing list - add new TL(s)
  * [x] add TL to chairs/leads meeting
  * [x] tag-security repo PR:
    * [x] Update codeowners, github settings, README (TOC Liaisons and chairs
      have admin access, tech leads have push access).
    * [x] Link to official vote email list message in PR descriptions
    * [x] Add STAG milestone to track STAG rep for TL
  * [x] [TOC Repo update](https://github.com/cncf/toc/blob/main/tags/cncf-tags.md#tag-security)
  * [x] Verify new TLs have zoom credentials
  * [x] Introduce new TL selection, in the next steering committee meeting slide
  * [x] YouTube Channel
    * [x] invite new TLs (if needed)
    * [x] give "managers" permission

## Announce

* [x] Announce the vote
  * [x] #tag-security slack message
  * [x] email message to the tag-security list
  * [x] Security TAG meeting Announcement for each region

**Comment by jkjell** [comment]
All items completed.
