### ISSUE TITLE
Tech Lead Transition Checklist: Brandt Keller

### ISSUE THREAD

**Issue by brandtkeller** [cncf/tag-security#1361]
# Tech Lead Transition Checklist

This checklist should be copied into a new issue for when a new tech lead(s) is needed.

## Nomination

For nomination process please refer to [tech-lead-proposal-process](./tech-lead-proposal-process.md)

## Transfer

* [ ] Transfer Logistics
  * [x] #tag-security-chairs-and-tech-leads channel - add new TL(s)
  * [ ] tag-leadership mailing list - add new TL(s)
  * [x] add TL to chairs/leads meeting
  * [ ] tag-security repo PR:
    * [ ] Update codeowners, github settings, README (TOC Liaisons and chairs
      have admin access, tech leads have push access).
    * [ ] Link to official vote email list message in PR descriptions
    * [ ] Add STAG milestone to track STAG rep for TL
  * [x] [TOC Repo update](https://github.com/cncf/toc/blob/main/tags/tag-charters/security.md)
  * [ ] Verify new TLs have zoom credentials
  * [ ] Introduce new TL selection, in the next steering committee meeting slide
  * [ ] YouTube Channel
    * [ ] invite new TLs (if needed)
    * [ ] give "managers" permission

## Announce

* [ ] Announce the vote
  * [x] #tag-security slack message
  * [ ] email message to the tag-security list
  * [x] Security TAG meeting Announcement for each region

**Comment by matthewflannery** [comment]
@brandtkeller this looks good to close, I reviewed my own checklist and noted you have the same things.
