### ISSUE TITLE
update roadmap

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/tag-security#414]
Description: We need to update the roadmap.  Its not been updated in a long time and we have lots of things in flight. 
https://github.com/cncf/sig-security/blob/master/roadmap.md

TO DO
- [x] SIG Sponsor/Project Lead: @TheFoxAtWork 
- [x] Team: @ultrasaurus @pragashj 
- [X] update [history](https://github.com/cncf/sig-security/blob/master/roadmap.md) of what happened since May 2019 @ultrasaurus @lumjjb https://github.com/cncf/sig-security/pull/560
- [ ] link to [project boards](https://github.com/cncf/sig-security/projects) with some description of broader plans and how we use these
- [ ] add future items

**Comment by TheFoxAtWork** [comment]
Tasked to TLs and Co-Chairs for next discussion.  We've got lots of great things being proposed.

**Comment by TheFoxAtWork** [comment]
this issue is completed
