### ISSUE TITLE
Chair Transition Checklist

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/tag-security#684]
* [X] Nomination
  * [X] TOC-liaison slack discussion/approval
  * [X] Cochair-TL meeting announcement
  * [X] TAG Security meeting announcement (should be all meetings)
  * [X] TOC email list official nomination
  * [X] #tag-security slack message with link with email nomination
  * [X] TOC meeting presentation  
* [X] Vote - official count recorded by @amye https://lists.cncf.io/g/cncf-toc/message/5884
* [x] Xfer logistics
    * [x] #tag-chairs slack channel - add new chairs
    * [x]  tag-chairs mailing list - add new chairs
    * [x] #tag-security-cochairs channel - add new chairs 
    * [x] #tag-security-cochairs-emeritus - add outgoing chairs
    * [x] #tag-security-toc-liaison - add new chairs
    * [X] co-chair meeting — add new co-chairs & doc sharing
    * [x] TOC Liaison meeting
        * [x] check if time works for new chairs
        * [X] xfer calendar ownership if needed -- now owned by @TheFoxAtWork 
        * [x] add new co-chairs to calendar invite
        * [x] share meeting notes doc 
    * [x] choose new chair representatives for Security TAG [on-going projects](https://github.com/cncf/tag-security#on-going-projects) if needed
    * [x] tag-security repo PR: 
        * [x] Update code owners, github settings, README (TOC liaisons and chairs have admin access, tech leads have push access. )
        * [x] Link to official vote email list message in PR description
    * [x] [toc repo update](https://github.com/cncf/toc/tree/main/tags) - https://github.com/cncf/toc/pull/668
    * [x] Service Desk access
    * [x] email lists
       * [x] update email list membership
       * [x] chairs should have moderator role
       * [x] remove old chairs from chairs list
    * [x] verify new chairs have zoom credentials
    * [x] YouTube channel
      * [x] invite new chairs (if needed)
      * [x] give "owners" permission
* [x] Announce vote
  * [x] #tag-security slack message
  * [x] [email message to tag-security list](https://lists.cncf.io/g/cncf-tag-security/topic/new_chairs/83373377?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,83373377)
  * [x] TAG Security meeting announcement APAC Jun 7 (JJ)
  * [x] TAG Security meeting announcement EU-AM Jun 9 (Emily)

* [x] turn this list into a PR (markdown doc in /governance), so we have it for next time

**Comment by TheFoxAtWork** [comment]
Youtube permissions should be set as follows:
* Chairs are owner
* TLs are Manager
* Chair emeritus becomes Manager

**Comment by TheFoxAtWork** [comment]
Chair Emeritus continues with Tech lead permissions @lumjjb will submit PR.

**Comment by lumjjb** [comment]
PR for Chair Emeritus role: https://github.com/cncf/tag-security/pull/685

**Comment by lumjjb** [comment]
Checking off Update code owners, github settings, README  with #688 and #689

**Comment by lumjjb** [comment]
Checking off "choose new chair representatives for Security TAG on-going projects if needed". I believe this was resolved during the meeting, reflected in #688

**Comment by lumjjb** [comment]
checked "chairs should have moderator role"  - addressed by service ticket 
checked  "Service Desk access" - addressed by service ticket

**Comment by lumjjb** [comment]
We've been added to the tag chairs mailing list, added an item in the list

**Comment by ultrasaurus** [comment]
this looks complete -- @TheFoxAtWork @lumjjb anything left to do?

**Comment by TheFoxAtWork** [comment]
The TOC pr needs merged in unless the outstanding PR is good enough?

**Comment by ultrasaurus** [comment]
I just ping'd @amye via slack on the PR merge -- would be good to check all the boxes before closing this :)

**Comment by ultrasaurus** [comment]
All items now checked off!
