### ISSUE TITLE
Cloud Native Security Whitepaper v2

### ISSUE THREAD

**Issue by PushkarJ** [cncf/tag-security#747]
Working draft (RFC ends April 27): https://docs.google.com/document/d/1fftLBt3XjDzyYQisEKH3TZXL1QnT_cHIbBnFtW98UOs/edit

## Description 
Original security whitepaper (#138) was published in Nov 2020, about 9 months ago. It is now time to update the paper and publish v2 by Kubecon EU 2022 (by which time paper will be 18 months old) to ensure the content stays relevant and useful.

## Impact 
Since publication of v1, Security TAG has made a lot of progress through ongoing work on several supplementary docs, websites, audio version, maps and other papers. In general, the security understanding of cloud native environments has also evolved with growing focus on ransomware and supply chain security. We have also received feedback on the paper's content and its distribution through cloud native security survey and retrospective.

Additionally, there have been several small updates in the repo, made to the original content that have improved the readability and quality of the paper. Bringing this all together merits publishing the second version, in accordance, with original goal of keeping the content always up to date. 

## Scope
Several tasks are in progress and there are some that would need further work

## Tasks 
- [x] @PushkarJ: #828
- [x] @sayantani11:  #829 
- [x] @savitharaghunathan:  #830 
- [x] @devadvocado: #832
- [x] @PushkarJ: #833
- [x] @faisalrazzak: #834
- [x] @mateuszpruchniak: #831
- [x] @fkautz @mnm678 @pratiklotia @mateuszpruchniak #844 
- [x] @fkautz @joelerbork #828 
- [x] @PushkarJ : #521 

**Meta Deliverables:**
- [x] Decide whether audio version and translations trail written copy with n-1 cadence or do we publish it together
- [x] Consider renaming the whitepaper to something else based on the content
- [x] Consider different format of artifacts for v2 (epub, html, mobi)
- [x] Revisit distribution strategy so that the content reaches the intended audience i.e. end users
- [x] Track the citations for CNSWP v1 and add it in appendix of v2

Meta tasks:
- [x] Security TAG Leadership Representative: @lumjjb 
- [x] Project leader(s): @PushkarJ 
- [x] Project Members: Please comment if you are interested to join
- [x] Slack Channel: # tag-security-whitepaper
- [x] Meeting Time & Day: 01/12/2022, Wednesday 9AM - 10 AM PT
- [x] Meeting Notes (link): https://docs.google.com/document/d/1nJvDNhZedYxAhk1zKDjqgGaw0OKHtAnPFNs-MO23ELk/edit#heading=h.sxcjkdwxafg4 
- [x] Retrospective

--------
## Project Schedule
| TODO | Milestone | Estimated time | Actual date
| -- | -- | -- |--|
| :heavy_check_mark:  | Audience, Goals, & refining scope | 1 week | Nov 30 2021
| :heavy_check_mark:  | Tasking Assignment | 1 week | Dec 7 2021
| :heavy_check_mark:  | Content Rough-in | 2-3 weeks | Feb 28 2022
| :heavy_check_mark: | Collaborative Review | 2 weeks | March 15 2022
| :heavy_check_mark: | Executive Summary and content wrap up | 2 weeks | March 30 2022
| :heavy_check_mark: | Narrative Voice | 1-2 weeks | March 30 2022
| :heavy_check_mark: | Final Group Review | 1 week | April 6 2022
| :heavy_check_mark: | Community Review / Public comment adjudication  | 2-3 weeks | April 27 2022
| :heavy_check_mark: | CNCF publishing engagement | ~2-3 weeks | May 7 2022
| :heavy_check_mark: | Addition to the repo | 1 week | May 15 2022
| :heavy_check_mark: | Blog post and publishing coordination | 2-3 weeks | May 15 2022

**Comment by chasemp** [comment]
Seems like a lot of great metadata and organization tie in.  What's the thinking on revising the content itself?  (not suggesting just asking)

Interested in helping potentially :)

**Comment by pratiklotia** [comment]
thanks for detailed info, Pushkar. I'm interested in contributing.

**Comment by axelsimon** [comment]
Tagging myself as i'm interested in participating in this!

**Comment by PushkarJ** [comment]
> Seems like a lot of great metadata and organization tie in. What's the thinking on revising the content itself? (not suggesting just asking)
> 
> Interested in helping potentially :)

Hey Chase, great to see you are interested to continue the work from v1. My thinking for revising the existing content itself is to update the content for brevity, remove mention of things that are deprecated in favor of new state of the art. 

Additionally, would love to cross link sections in #737 to each section in the whitepaper so folks can jump to implementation details or recommendation from a requirement as part of an engaging learning experience :)

**Comment by ragashreeshekar** [comment]
This sounds good @PushkarJ, I'm interested to join.

**Comment by sayantani11** [comment]
Sounds good. Interested to join.

**Comment by mayocream** [comment]
Sounds good. Interested in contributing.

**Comment by PushkarJ** [comment]
Our friendly bot, reminded me that it is time to start working on version 2!! 

I will bring this up in our weekly call tomorrow (11/03) and we can get started on this :) Excited 🎉

**Comment by lumjjb** [comment]
Perfect, please remind me to bring up some of the discussions we had with NIST around ideas to augment the whitepaper !

**Comment by captainarcher** [comment]
I am interested in helping on this

**Comment by faisalrazzak** [comment]
For the NIST SSDF mapping work, I would like to contribute as well.

**Comment by JonZeolla** [comment]
@PushkarJ I'm interested in helping with v2

**Comment by jedsalazar** [comment]
I am interested in helping with this!

**Comment by savitharaghunathan** [comment]
@PushkarJ I am late to the party. Interested in helping out if you haven't maxed out on volunteers.

**Comment by PushkarJ** [comment]
No hard limit on contributors. So everyone is welcome!!

**Comment by sayantani11** [comment]
Interested to help!

**Comment by sachinkumarsingh092** [comment]
Hi @PushkarJ, I'm interested in helping out with this. Just one suggestion: Can we use LaTeX for the paper instead of google docs? IMO it will produce a much better-looking and version-controlled whitepaper. WDYT?

**Comment by freddyfernando** [comment]
Happy to contribute. This is my favourite project of late. 🚀

**Comment by idcrosby** [comment]
I'm interested in contributing!

**Comment by balasu** [comment]
I think below is 2022 nt 2021. 
 - First draft is ready: Jan 2022

**Comment by PushkarJ** [comment]
@balasu yes thank you! Updated now 😊

**Comment by devadvocado** [comment]
Would like to help as well, put me to work

**Comment by balasu** [comment]
> 
> 
> @balasu yes thank you! Updated now 😊

Thnks happy to contribute if anything needs to be added

**Comment by cavdarturgay** [comment]
Hi  @PushkarJ
I am also interested to help.

Best regards.

**Comment by oxeye-ron** [comment]
Count me in :)

**Comment by akashkaveti** [comment]
Interested to contribute :)

**Comment by IAXES** [comment]
Likewise: count me in :)

**Comment by ak-secops** [comment]
I'm interested in contributing!

**Comment by PushkarJ** [comment]
Thank you all so much for your interest. I will share a meeting invite for Wed Nov. 17 9 AM PT, to make introduction, finalize the scope and decide next steps soon. 

Please find me on https://cloud-native.slack.com/archives/CDJ7MLT8S (slack handle: PJ) if you want to reach out to me 1:1.

**Comment by mateuszpruchniak** [comment]
I have been working as an architect IT/cloud architect in the financial industry (highly regulated environments) for several years I would like to contribute, count me in! Thanks!

**Comment by PushkarJ** [comment]
Hi All, here is the agenda and the meeting details for our first meeting: https://docs.google.com/document/d/1nJvDNhZedYxAhk1zKDjqgGaw0OKHtAnPFNs-MO23ELk/edit#heading=h.sxcjkdwxafg4 (link should be accessible for all)

To reiterate, we will meet **Wed., Nov. 17, 9 AM to 10 AM PST**. (This will be followed by our regularly scheduled TAG Security meeting). 

We will record the meeting in case the time is inconvenient. For the ones who can join, I can't wait to meet you all ☺️

**Comment by PushkarJ** [comment]
Just reminder, we are meeting tomorrow (Wed, 11/17/21) 9AM PST !! Here's the link with details on how to join: https://docs.google.com/document/d/1nJvDNhZedYxAhk1zKDjqgGaw0OKHtAnPFNs-MO23ELk/edit#heading=h.sxcjkdwxafg4

**Comment by fkautz** [comment]
I joined the first meeting and intend to participate.

**Comment by maorkuriel** [comment]
Thanks for the detailed info, @PushkarJ 
I'm interested in contributing.

**Comment by PushkarJ** [comment]
Hi All, Just added new dedicated [issues](https://github.com/cncf/tag-security/issues?q=is%3Aissue+is%3Aopen+%5BCNSWP+v2%5D) that represent the deliverables for v2. 

Please check the description of this parent issue for more context. The issues with "Need Owner" prefix are the ones up for grabs. If you want to work on them, please add a comment on that particular issue so one of the Tech Leads / Chairs can assign it to you! There can be more than one assignee to the same issue as long as you all can collaborate and divide the work between yourselves :) 

As a reminder, we will reconvene meeting in Jan but don't let that stop you from making progress on them in an async manner. Also, its okay to make updates on a google doc or hackmd or wherever for your first draft. We will pull them all together into one place when we meet together!! Good luck and leave a comment if you have any questions.

**Comment by bredamatt** [comment]
Interested in helping out as well!

Best,
Mattia

**Comment by PushkarJ** [comment]
Thank you @sayantani11 , @savitharaghunathan , @devadvocado , @faisalrazzak , @captainarcher , @mateuszpruchniak for raising your hand up to take ownership of the deliverable issues. 

Let's meet up in the upcoming week **Jan 12, Wed, 9-9:45 AM PT** to get together and discuss your progress and plans for completing these deliverables. Bring your questions and let's have some fun at work :) . If you want to add the meeting to your calendars, please click on this [link](https://calendar.google.com/event?action=TEMPLATE&tmeid=MTg1ZThlODU1aHM3NDFzb2VocGQ5NzczZHUgb2t0c3RwdWU4Y2E4cnFkYWY3Mzg1cWJjdGtAZw&tmsrc=oktstpue8ca8rqdaf7385qbctk%40group.calendar.google.com). 

The meeting minutes and zoom details can be found [here](https://docs.google.com/document/d/1nJvDNhZedYxAhk1zKDjqgGaw0OKHtAnPFNs-MO23ELk/edit#heading=h.4gcdi8xdihx6). 

NOTE: For others who are interested to contribute you are welcome to join as we always have more to do and help each other out!

Leave a comment here or find me on CNCF slack (channel: #tag-security-whitepaper) if you have trouble joining the meeting!

**Comment by PushkarJ** [comment]
Thank you all for meeting today ❤️!! 

Please hop on over to slack and check out the [next steps] (https://cloud-native.slack.com/archives/C017K5AN70T/p1642032270020200)

**Comment by fdegir** [comment]
I made a comment on [SSF RFC doc](https://docs.google.com/document/d/15M_Mzfqy634E_sqoslmOXsZJl4TedpbXpBjOfz-hnXk/edit#) regarding the potential benefits of generating some kind of delta report in addition to SBOM itself in order to ease the effort to identify issues as they happen and components that cause them. The reason for this is that if one has a delta report, it would limit the no of components to work with as oppose to SBOMs with potentially thousands of components while working with issues. 

@lumjjb pointed this issue as a place to highlight the topic of delta report and I also found [the cloud-native-security-whitepaper-v2
](https://docs.google.com/document/d/1fftLBt3XjDzyYQisEKH3TZXL1QnT_cHIbBnFtW98UOs/edit#) where page 36 looks like the potential place to talk about delta report. However, I wanted to get opinion of the community about this idea before providing anything else.

**Comment by PushkarJ** [comment]
@fdegir go ahead and make your updates. Correct page number though would be 34-35 under supply chain security

**Comment by fdegir** [comment]
Thanks @PushkarJ. Added a new paragraph on page 35.

**Comment by PushkarJ** [comment]
Whitepaper v2 is now open for Public comment. RFC stage ends April 27 2022. You can find the paper for review here: https://docs.google.com/document/d/1fftLBt3XjDzyYQisEKH3TZXL1QnT_cHIbBnFtW98UOs/edit

**Comment by jkowall** [comment]
Left comments, rewrote parts of it, and hopefully improved it after an extensive review. Sorry, I was not aware this was being revised, I should have tried to join some calls but not enough time.

**Comment by PushkarJ** [comment]
@jkowall thank you so much for your generous updates and exhaustive read!! The paper is in better shape because of it :)

**Comment by jkowall** [comment]
@PushkarJ my pleasure, feel free to move me to author or reviewer. I am happy to take another look anytime or add sections as needed.

**Comment by PushkarJ** [comment]
@jkowall already added you as reviewer :) We are bit late in terms of timeline to add new content/section though but please open an issue (suggestion) with what you have in mind, so we don't lose track of it and can figure out which artifact (perhaps v3 of this paper) we could incorporate it in.

**Comment by p0bailey** [comment]
Hi @PushkarJ,

Thanks for the great work, just wanted to highlight an error inside the PDF https://github.com/cncf/tag-security/blob/main/security-whitepaper/v2/CNCF_cloud-native-security-whitepaper-May2022-v2.pdf 

In the PDF figure 4 is a duplication of [distribute](https://github.com/cncf/tag-security/blob/main/security-whitepaper/v2/cnswp-images/cnswp-v2-security-structural-model-distribute.png) whereas figure 4 should be [Deploy figure 4](https://github.com/cncf/tag-security/blob/main/security-whitepaper/v2/cnswp-images/cnswp-v2-security-structural-model-deploy.png) 

Thanks,

Phillip

**Comment by PushkarJ** [comment]
@p0bailey sorry for the delayed response. You are absolutely right. The markdown seems to not have this discrepancy (anymore). So we will fix this in the next update to the PDF

**Comment by PushkarJ** [comment]
Closing this issue now with creation of #975 . Thank you all for the wonderful collaboration, contributions and camaraderie. 

Great opportunity to lead creation and publication of the next version for existing and new contributors. More details in the linked issue and I will be happy to chat more if anyone has more questions :)

**Comment by p0bailey** [comment]
@PushkarJ thanks for the heads up. Looking forward to downloading the updated PDF. Great work!

Phillip
