### ISSUE TITLE
TL Transition Checklist

### ISSUE THREAD

**Issue by lumjjb** [cncf/tag-security#847]
As with the [Chair Transition Checklist](https://github.com/cncf/tag-security/blob/main/governance/chair-transition.md), it would be useful to have one for TLs as well.

Populating this as things come up:

## Nomination

(refer to https://github.com/cncf/tag-security/blob/main/governance/tech-lead-proposal-process.md)

## Transfer

* [ ] Transfer Logistics
  * [ ] #tag-security-chairs-and-tech-leads channel - add new TL(s)
  * [ ] tag-leadership mailing list - add new TL(s)
  * [ ] add TL to chairs/leads meeting
  * [ ] add TL to [github team](https://github.com/orgs/cncf/teams/tag-security/)
  * [ ] tag-security repo PR:
    * [ ] Update codeowners, github settings, README (TOC Liaisons and chairs
      have admin access, tech leads have push access).
    * [ ] Link to official vote email list message in PR descriptions
    * [ ] Add STAG milestone to track STAG rep for TL
  * [ ] Verify new TLs have zoom credentials
  * [ ] YouTube Channel
    * [ ] invite new TLs (if needed)
    * [ ] give "managers" permission

## Announce

* [ ] Announce the vote
  * [ ] #tag-security slack message
  * [ ] email message to the tag-security list
  * [ ] Security TAG meeting Announcement for each region

**Comment by lumjjb** [comment]
@cncf/tag-security

**Comment by PushkarJ** [comment]
I like this idea and can help create a PR for all of us to review / collaborate on :) But, this sounds like a good first issue, which I would be happy to help a new contributor on.

**Comment by weideng1** [comment]
happy to tackle this one as my first issue.

**Comment by PushkarJ** [comment]
Thank you for working on this @weideng1 Here's my suggestion on how to proceed:

1. Fork the tag-security repo
2. Add a new file here https://github.com/cncf/tag-security/blob/main/governance/tech-lead-transition.md in your fork
3. Copy the following content in the new file

  ```
  # Tech Lead transition checklist
  
  This checklist should be copied into a new issue for when a new tech lead(s) is needed.
  
  ## Nomination
  
  For nomination process please refer to [tech-lead-proposal-process](./tech-lead-proposal-process.md)
  
  ## Transfer
  
  * [ ] Transfer Logistics
    * [ ] #tag-security-chairs-and-tech-leads channel - add new TL(s)
    * [ ] [tag-leadership mailing list](https://lists.cncf.io/g/cncf-tag-security-leads) - add new TL(s)
    * [ ] add TL to chairs/leads meeting
    * [ ] add TL to [github team](https://github.com/orgs/cncf/teams/tag-security/)
    * [ ] tag-security repo PR:
      * [ ] Update codeowners, github settings, README (TOC Liaisons and chairs
        have admin access, tech leads have push access).
      * [ ] Link to official vote email list message in PR descriptions
      * [ ] Add STAG milestone to track STAG rep for TL
    * [ ] Verify new TLs have zoom credentials
    * [ ] Introduce new TL selection, in the next steering committee meeting slide
    * [ ] YouTube Channel
      * [ ] invite new TLs (if needed)
      * [ ] give "managers" permission
  
  ## Announce
  
  * [ ] Announce the vote
    * [ ] #tag-security slack message
    * [ ] email message to the tag-security list
    * [ ] Security TAG meeting Announcement for each region
  ```

4. Commit and push your changes. Example of good commit message: https://github.com/cncf/tag-security/pull/846/commits/1323762f8fbbd404da30f7bb6bbbb8b1e6d89311
5. Submit a PR
6. Make sure to add `Fixes #847` in the PR description
7. Let the jobs run and look for any failures on linting, spelling, etc. 
8. Update content as appropriate to fix any errors until all jobs are passing
9. Reach out by tagging me using my handle`@pushkarj` in the PR if you have any questions or get stuck

After this, one of us (TL/Co-chair) will review the code and then approve it :)
