### ISSUE TITLE
Chair Transition Checklist - Andrew Martin

### ISSUE THREAD

**Issue by lumjjb** [cncf/tag-security#879]
Checklist for @sublimino 

## Nomination

This serves to augment the [Security TAG Chair proposal
process](chair-proposal-process.md) with specific items that must be completed.

* [x] Nomination
* [x] Vote - official count recorded and posted - https://lists.cncf.io/g/cncf-toc/message/6764

## Transfer

* [x] Transfer Logistics
  * [x] #tag-chairs slack channel - add new chair(s)
  * [x] tag-chairs mailing list - add new chair(s) - invite sent
  * [x] #tag-security-cochairs channel - add new chair(s)
  * [x] #tag-security-cochairs-emeritus - add outgoing chair(s)
  * [x] #tag-security-toc-liaison - add new chair(s)
  * [x] Co-chair meeting - add new co-chairs and add doc sharing
  * [x] transfer ownership of co-chair meeting calendar invite - NA
    and tech lead calendar invite - if applicable
  * [x] TOC Liaison meeting
    * [x] Check if the time still works for new chair(s)
    * [x] Transfer calender ownership if needed
    * [x] Add new co-chair(s) to calendar invitation
    * [x] Share meeting notes doc
  * [x] Choose new chair representative for Security TAG [on-going
    projects](https://github.com/cncf/tag-security#on-going-projects) if needed.
  * [x] add chair to [github team](https://github.com/orgs/cncf/teams/sig-security/)
  * [x] tag-security repo PR:
    * [x] Update codeowners, github settings, README (TOC Liaisons and chairs
      have admin access, tech leads have push access).
    * [x] Link to official vote email list message in PR descriptions
  * [x] [TOC Repo update](https://github.com/cncf/toc/blob/main/tags/security.md) - created PR
  * [x] [Service Desk Access](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1)
  * [x] Update email lists
    * [x] update email list membership
    * [x] chairs should have moderator role
    * [x] remove old chairs from chairs list
  * [x] Verify new chairs have zoom credentials
  * [x] YouTube Channel
    * [x] invite new chairs (if needed)
    * [x] give "owners" permission

## Announce

* [x] Announce the vote
  * [x] #tag-security slack message
  * [x] email message to the tag-security list
  * [x] Security TAG meeting Announcement for each region
